2021-11-26 19:59:20,343 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:02:00,067 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:02:00,926 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:02:07,999 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:02:08,800 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:02:10,126 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:02:10,872 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:02:16,727 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:02:17,721 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:02:34,635 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:02:35,477 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:02:39,058 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:02:40,084 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:02:41,542 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:02:42,665 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:02:50,271 [INFO] accounts.views: username = root
2021-11-26 20:02:50,271 [INFO] accounts.views: password = rootroot
2021-11-26 20:04:30,744 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:04:31,528 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:04:34,344 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:04:35,322 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:04:37,186 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:04:38,057 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:04:39,432 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:04:40,229 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:04:43,027 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:04:44,171 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:04:47,006 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:04:47,772 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:05:35,053 [INFO] accounts.views: username = root
2021-11-26 20:05:35,053 [INFO] accounts.views: password = rootroot
2021-11-26 20:05:35,252 [INFO] accounts.views: use = None
2021-11-26 20:08:48,823 [INFO] accounts.views: username = hyoju
2021-11-26 20:08:48,823 [INFO] accounts.views: password = 1234
2021-11-26 20:08:48,990 [INFO] accounts.views: use = hyoju
2021-11-26 20:14:02,192 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-26 20:14:03,103 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:14:10,240 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-26 20:14:11,085 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:14:17,809 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-26 20:14:19,007 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:18:29,998 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:18:36,087 [INFO] accounts.views: username = root
2021-11-26 20:18:36,088 [INFO] accounts.views: password = rootroot
2021-11-26 20:18:36,414 [INFO] accounts.views: use = None
2021-11-26 20:20:49,289 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:20:58,803 [INFO] accounts.views: username = root
2021-11-26 20:20:58,803 [INFO] accounts.views: password = rootroot
2021-11-26 20:20:58,987 [INFO] accounts.views: user = None
2021-11-26 20:21:02,872 [INFO] accounts.views: username = root
2021-11-26 20:21:02,872 [INFO] accounts.views: password = rootroot
2021-11-26 20:21:03,049 [INFO] accounts.views: user = None
2021-11-26 20:25:09,018 [INFO] accounts.management.commands.inituser: init_username = root
2021-11-26 20:25:09,018 [INFO] accounts.management.commands.inituser: init_password = 1234
2021-11-26 20:25:09,018 [INFO] accounts.management.commands.inituser: init_action = reset
2021-11-26 20:25:35,838 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:25:54,286 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 20:25:59,863 [INFO] accounts.views: username = root
2021-11-26 20:25:59,863 [INFO] accounts.views: password = 1234
2021-11-26 20:26:00,189 [INFO] accounts.views: user = None
2021-11-26 20:27:30,441 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 20:27:31,227 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:12:42,432 [INFO] accounts.management.commands.inituser: init_username = root
2021-11-26 21:12:42,432 [INFO] accounts.management.commands.inituser: init_password = 1234
2021-11-26 21:12:42,432 [INFO] accounts.management.commands.inituser: init_action = create_admin
2021-11-26 21:12:42,447 [INFO] accounts.management.commands.inituser: user create = root
2021-11-26 21:12:50,824 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:12:59,710 [INFO] accounts.views: username = root
2021-11-26 21:12:59,710 [INFO] accounts.views: password = 1234
2021-11-26 21:12:59,887 [INFO] accounts.views: user = root
2021-11-26 21:13:12,742 [INFO] accounts.views: username = root
2021-11-26 21:13:12,742 [INFO] accounts.views: password = 1234
2021-11-26 21:13:12,912 [INFO] accounts.views: user = root
2021-11-26 21:13:39,277 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:13:40,611 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:13:43,108 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:13:44,050 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:13:52,339 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:13:53,260 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:17:23,797 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:17:24,522 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:17:45,568 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:17:46,539 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:17:48,318 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:17:49,170 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:17:55,448 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:17:56,548 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:18:11,427 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:18:12,357 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:18:13,974 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:18:14,727 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:18:23,872 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:18:24,601 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:18:30,212 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:18:31,239 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:19:02,072 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:19:02,920 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:19:06,824 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:19:07,823 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:19:13,806 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:19:14,866 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:19:56,516 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-26 21:19:57,585 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:19:59,296 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-26 21:20:00,169 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:20:14,933 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:20:15,753 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:20:29,521 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:20:30,407 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:21:00,559 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:21:31,144 [ERROR] django.request: Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py", line 13, in signup
    user = User.objects.create(
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
TypeError: create() takes 1 positional argument but 2 were given
2021-11-26 21:22:11,906 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:22:12,942 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:22:21,291 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:22:22,219 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:22:45,200 [ERROR] django.request: Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py", line 13, in signup
    user = User.objects.create(username=request.POST['username'], email=request.POST['email'], dept=request.POST['dept'])
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: user.username
2021-11-26 21:24:04,936 [INFO] accounts.management.commands.inituser: init_username = root
2021-11-26 21:24:04,936 [INFO] accounts.management.commands.inituser: init_password = 1234
2021-11-26 21:24:04,937 [INFO] accounts.management.commands.inituser: init_action = create_admin
2021-11-26 21:24:04,952 [INFO] accounts.management.commands.inituser: user create = root
2021-11-26 21:24:10,156 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:24:32,935 [INFO] accounts.views: username = root
2021-11-26 21:24:32,936 [INFO] accounts.views: password = 123456
2021-11-26 21:24:33,112 [INFO] accounts.views: user = None
2021-11-26 21:25:00,468 [INFO] accounts.views: username = root
2021-11-26 21:25:00,469 [INFO] accounts.views: password = 1234
2021-11-26 21:25:00,650 [INFO] accounts.views: user = root
2021-11-26 21:25:25,642 [ERROR] django.request: Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py", line 13, in signup
    user = User.objects.create(username=request.POST['username'], email=request.POST['email'], dept=request.POST['dept'])
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\contrib\auth\base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: user.username
2021-11-26 21:28:24,370 [INFO] accounts.views: username = hj
2021-11-26 21:28:24,370 [INFO] accounts.views: password = 123456
2021-11-26 21:28:24,376 [INFO] accounts.views: user = None
2021-11-26 21:29:49,445 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:29:50,465 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:29:55,737 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:29:56,690 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:29:59,516 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:30:00,600 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:30:04,701 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:30:05,617 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:30:28,874 [INFO] accounts.views: user = tmp
2021-11-26 21:30:40,385 [INFO] accounts.views: username = tmp
2021-11-26 21:30:40,385 [INFO] accounts.views: password = 123
2021-11-26 21:30:40,391 [INFO] accounts.views: user = None
2021-11-26 21:32:19,625 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:32:20,431 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:32:28,599 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:32:29,384 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:32:35,543 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:32:36,501 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:32:44,630 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:32:45,536 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:33:07,713 [INFO] accounts.views: user = tt
2021-11-26 21:33:07,714 [INFO] accounts.views: user = 1234
2021-11-26 21:33:57,326 [INFO] accounts.views: username = hj
2021-11-26 21:33:57,326 [INFO] accounts.views: password = 123456
2021-11-26 21:33:57,329 [INFO] accounts.views: user = None
2021-11-26 21:34:02,203 [INFO] accounts.views: username = hj
2021-11-26 21:34:02,204 [INFO] accounts.views: password = 1234
2021-11-26 21:34:02,207 [INFO] accounts.views: user = None
2021-11-26 21:34:06,023 [INFO] accounts.views: username = root
2021-11-26 21:34:06,023 [INFO] accounts.views: password = 1234
2021-11-26 21:34:06,199 [INFO] accounts.views: user = root
2021-11-26 21:35:09,404 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:35:10,414 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:35:14,384 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:35:15,416 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:35:49,930 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:36:35,782 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:36:54,203 [INFO] accounts.views: username = root
2021-11-26 21:36:54,204 [INFO] accounts.views: password = 1234
2021-11-26 21:36:54,418 [INFO] accounts.views: user = root
2021-11-26 21:37:14,032 [INFO] accounts.views: user = hyoju
2021-11-26 21:37:14,032 [INFO] accounts.views: user = 1234
2021-11-26 21:42:20,593 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:42:21,498 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:42:24,366 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-26 21:42:25,568 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 21:46:02,926 [INFO] accounts.views: username = root
2021-11-26 21:46:03,113 [INFO] accounts.views: user = root
2021-11-26 21:46:16,196 [INFO] accounts.views: username = hyoju
2021-11-26 21:46:16,370 [INFO] accounts.views: user = None
2021-11-26 21:46:27,527 [INFO] accounts.views: username = hyoju
2021-11-26 21:46:27,697 [INFO] accounts.views: user = hyoju
2021-11-26 22:50:53,764 [INFO] accounts.views: username = root
2021-11-26 22:50:53,953 [INFO] accounts.views: user = root
2021-11-26 22:52:24,178 [ERROR] django.request: Internal Server Error: /faq/create/
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 29, in create
    return render(request, 'create.html')
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
2021-11-26 22:52:27,089 [ERROR] django.request: Internal Server Error: /faq/create/
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 29, in create
    return render(request, 'create.html')
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
2021-11-26 22:53:09,997 [ERROR] django.request: Internal Server Error: /faq/create/
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 29, in create
    return render(request, 'create.html')
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
2021-11-26 22:53:42,431 [ERROR] django.request: Internal Server Error: /faq/create/
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 29, in create
    return render(request, 'create.html')
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
2021-11-26 22:53:43,362 [ERROR] django.request: Internal Server Error: /faq/create/
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 29, in create
    return render(request, 'create.html')
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
2021-11-26 22:53:50,222 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 15, in home
    return render(request,'home.html', {'blogs':blogs,'posts':posts} )
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
2021-11-26 22:54:22,522 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 22:54:25,432 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 15, in home
    return render(request,'home.html', {'blogs':blogs,'posts':posts} )
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user' not found. 'user' is not a valid view function or pattern name.
2021-11-26 22:55:12,376 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 15, in home
    return render(request,'home.html', {'blogs':blogs,'posts':posts} )
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'management' not found. 'management' is not a valid view function or pattern name.
2021-11-26 22:55:35,583 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-26 22:55:36,476 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 22:55:42,489 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-26 22:55:43,303 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 22:55:52,414 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-26 22:55:53,177 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 22:55:57,782 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-26 22:55:58,926 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 22:56:24,012 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-26 22:56:25,025 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 22:56:57,439 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-26 22:56:58,455 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 22:57:01,349 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-26 22:57:02,711 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 22:57:14,546 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-26 22:57:15,277 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-26 22:57:34,027 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-26 22:57:35,340 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:09:01,513 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:09:06,572 [WARNING] django.request: Not Found: /favicon.ico
2021-11-28 19:09:12,888 [INFO] accounts.views: username = admin
2021-11-28 19:09:13,057 [INFO] accounts.views: user = admin
2021-11-28 19:15:34,672 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:15:35,732 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:15:40,667 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:15:41,409 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:15:55,860 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:15:56,863 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:15:58,712 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:15:59,553 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:16:01,046 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:16:01,902 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:16:27,424 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:16:28,381 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:16:38,428 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:16:39,322 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:16:47,136 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:16:47,933 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:16:49,570 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:16:50,505 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:17:19,222 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:17:19,983 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:17:29,819 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:17:30,622 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:17:45,330 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:17:46,640 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:18:05,240 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:18:06,338 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:18:15,617 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:18:16,452 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:18:21,080 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:18:21,931 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:18:24,418 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:18:25,302 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:18:40,617 [ERROR] django.request: Internal Server Error: /faq/management
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 22, in management
    user = User.objects.filter(admintype='user')
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\query.py", line 1286, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\query.py", line 1112, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\query.py", line 1539, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'admintype' into field. Choices are: admin_type, dept, email, id, last_login, logentry, password, username
2021-11-28 19:19:36,760 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:19:37,584 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:20:06,254 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:20:06,979 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:20:10,858 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:20:12,030 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:21:02,309 [INFO] accounts.views: username = admin
2021-11-28 19:21:02,473 [INFO] accounts.views: user = admin
2021-11-28 19:21:51,464 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:21:52,298 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:22:08,063 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:22:09,064 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:27:07,511 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:27:08,372 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:27:16,560 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:27:17,413 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:27:21,343 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:27:22,121 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:27:26,003 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:27:27,333 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:27:57,567 [WARNING] django.request: Not Found: /static/delete.png
2021-11-28 19:27:57,568 [WARNING] django.request: Not Found: /static/update.png
2021-11-28 19:28:38,302 [WARNING] django.request: Not Found: /static/update.png
2021-11-28 19:28:38,306 [WARNING] django.request: Not Found: /static/delete.png
2021-11-28 19:31:08,862 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:31:09,685 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:31:12,549 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:31:13,629 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:31:15,332 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:31:16,069 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:33:12,231 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:33:13,199 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:33:17,190 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 19:33:18,083 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 19:37:00,199 [INFO] accounts.views: username = admin
2021-11-28 19:37:00,378 [INFO] accounts.views: user = admin
2021-11-28 19:46:56,410 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2021-11-28 19:46:56,615 [WARNING] django.request: Bad Request: /
2021-11-28 19:58:28,119 [WARNING] django.request: Not Found: /static/update.png
2021-11-28 19:58:28,120 [WARNING] django.request: Not Found: /static/delete.png
2021-11-28 20:03:05,150 [INFO] accounts.views: username = admin
2021-11-28 20:03:05,329 [INFO] accounts.views: user = admin
2021-11-28 20:13:02,421 [INFO] accounts.views: username = 1234
2021-11-28 20:13:02,604 [INFO] accounts.views: user = 1234
2021-11-28 20:13:10,348 [INFO] accounts.views: username = admin
2021-11-28 20:13:10,520 [INFO] accounts.views: user = admin
2021-11-28 20:15:00,704 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 20:15:01,660 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:15:09,571 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 20:15:10,958 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:42:12,920 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 20:42:14,212 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:42:37,914 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 20:42:38,801 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:42:59,517 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 20:43:00,497 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:43:31,898 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 20:43:33,127 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:43:45,833 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 20:43:46,539 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:44:03,848 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 20:44:04,751 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:44:11,467 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 20:44:12,546 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:44:16,123 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 20:44:17,098 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:51:36,155 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 20:52:12,167 [INFO] accounts.views: username = admin
2021-11-28 20:52:12,331 [INFO] accounts.views: user = admin
2021-11-28 21:08:01,993 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 21:08:02,957 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:08:06,922 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 21:08:07,761 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:08:12,617 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 21:08:13,416 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:08:17,235 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 21:08:18,194 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:08:20,679 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 21:08:21,596 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:08:31,878 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 21:08:32,887 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:09:48,830 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:10:28,625 [INFO] accounts.views: username = admin
2021-11-28 21:10:28,797 [INFO] accounts.views: user = admin
2021-11-28 21:11:45,486 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\models.py changed, reloading.
2021-11-28 21:11:46,305 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:13:00,304 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:13:01,272 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:13:05,277 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:13:06,035 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:13:28,759 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:13:29,574 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:13:31,226 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:13:31,923 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:13:33,594 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:13:34,712 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:13:40,851 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:13:41,678 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:13:44,518 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:13:45,467 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:13:49,438 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:13:50,314 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:13:52,029 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:13:52,959 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:13:59,793 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:14:00,628 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:14:02,334 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:14:03,310 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:14:08,458 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:14:09,436 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:14:19,657 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py changed, reloading.
2021-11-28 21:14:20,523 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:14:58,970 [INFO] accounts.views: username = admin
2021-11-28 21:14:59,148 [INFO] accounts.views: user = admin
2021-11-28 21:16:17,376 [INFO] accounts.views: username = admin
2021-11-28 21:16:17,544 [INFO] accounts.views: user = admin
2021-11-28 21:18:33,867 [INFO] accounts.views: username = 1234
2021-11-28 21:18:34,053 [INFO] accounts.views: user = 1234
2021-11-28 21:18:34,100 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 19, in home
    return render(request,'home.html', {'blogs':blogs,'posts':posts} )
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit' not found. 'edit' is not a valid view function or pattern name.
2021-11-28 21:24:52,609 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-28 21:24:53,493 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:24:56,364 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-28 21:24:57,325 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:25:00,890 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-28 21:25:02,006 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:25:03,455 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-28 21:25:04,187 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:25:53,559 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 21:25:54,586 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:25:56,083 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 21:25:56,878 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:26:02,928 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 21:26:03,810 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:26:07,605 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 21:26:08,638 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:26:12,388 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-28 21:26:13,353 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:29:40,735 [INFO] accounts.views: username = admin
2021-11-28 21:29:40,898 [INFO] accounts.views: user = admin
2021-11-28 21:33:43,460 [ERROR] django.request: Internal Server Error: /faq/management
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "user.dept=='Software'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 23, in management
    return render(request, 'management.html', {'users': user})
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\cached.py", line 58, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=='Software'' from 'user.dept=='Software''
2021-11-28 21:33:45,050 [ERROR] django.request: Internal Server Error: /faq/management
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "user.dept=='Software'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 23, in management
    return render(request, 'management.html', {'users': user})
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\cached.py", line 58, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=='Software'' from 'user.dept=='Software''
2021-11-28 21:34:29,356 [ERROR] django.request: Internal Server Error: /faq/management
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "user.dept='Software'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 23, in management
    return render(request, 'management.html', {'users': user})
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\cached.py", line 58, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '='Software'' from 'user.dept='Software''
2021-11-28 21:34:50,089 [ERROR] django.request: Internal Server Error: /faq/management
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'user.dept==Software'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 23, in management
    return render(request, 'management.html', {'users': user})
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\cached.py", line 58, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==Software' from 'user.dept==Software'
2021-11-28 21:36:53,954 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:37:07,816 [INFO] accounts.views: username = admin
2021-11-28 21:37:07,993 [INFO] accounts.views: user = admin
2021-11-28 21:38:46,601 [INFO] accounts.views: username = admin
2021-11-28 21:38:46,774 [INFO] accounts.views: user = admin
2021-11-28 21:45:42,377 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-28 21:48:08,245 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\notice\settings.py changed, reloading.
2021-11-28 21:48:09,272 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 19:04:40,923 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 19:06:34,339 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\notice\settings.py changed, reloading.
2021-11-29 19:06:35,822 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 19:07:29,576 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 19:07:34,722 [WARNING] django.request: Not Found: /favicon.ico
2021-11-29 19:08:15,507 [INFO] accounts.views: username = admin
2021-11-29 19:08:15,731 [INFO] accounts.views: user = admin
2021-11-29 19:09:35,121 [INFO] accounts.views: username = admin
2021-11-29 19:09:35,358 [INFO] accounts.views: user = admin
2021-11-29 19:14:44,408 [INFO] accounts.views: username = 1234
2021-11-29 19:14:44,638 [INFO] accounts.views: user = 1234
2021-11-29 19:15:39,755 [INFO] accounts.views: username = admin
2021-11-29 19:15:39,981 [INFO] accounts.views: user = admin
2021-11-29 19:16:38,575 [WARNING] django.request: Not Found: /static/update.png
2021-11-29 19:16:38,583 [WARNING] django.request: Not Found: /static/delete.png
2021-11-29 19:16:42,862 [WARNING] django.request: Not Found: /static/update.png
2021-11-29 19:16:42,870 [WARNING] django.request: Not Found: /static/delete.png
2021-11-29 19:18:52,437 [INFO] accounts.views: username = 1234
2021-11-29 19:18:52,676 [INFO] accounts.views: user = 1234
2021-11-29 19:19:08,548 [WARNING] django.request: Not Found: /static/update.png
2021-11-29 19:19:08,549 [WARNING] django.request: Not Found: /static/delete.png
2021-11-29 19:19:21,199 [WARNING] django.request: Not Found: /static/update.png
2021-11-29 19:19:21,202 [WARNING] django.request: Not Found: /static/delete.png
2021-11-29 19:19:24,918 [WARNING] django.request: Not Found: /static/update.png
2021-11-29 19:19:24,927 [WARNING] django.request: Not Found: /static/delete.png
2021-11-29 19:19:33,586 [WARNING] django.request: Not Found: /static/update.png
2021-11-29 19:19:33,589 [WARNING] django.request: Not Found: /static/delete.png
2021-11-29 19:20:10,859 [WARNING] django.request: Not Found: /static/update.png
2021-11-29 19:20:10,861 [WARNING] django.request: Not Found: /static/delete.png
2021-11-29 19:42:32,022 [INFO] accounts.views: username = admin
2021-11-29 19:42:32,220 [INFO] accounts.views: user = admin
2021-11-29 20:01:44,502 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:01:48,448 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:01:49,985 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:01:51,094 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:02:44,870 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:02:45,933 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:06:10,341 [ERROR] django.request: Internal Server Error: /faq/eamil
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view faq.views.email didn't return an HttpResponse object. It returned None instead.
2021-11-29 20:06:53,532 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:06:55,043 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:07:11,003 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:07:12,513 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:08:05,127 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:08:06,774 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:08:10,425 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:08:11,800 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:08:42,071 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:08:49,206 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:08:59,552 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:09:01,056 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:09:07,053 [ERROR] django.request: Internal Server Error: /faq/eamil
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 108, in email
    return self.success(user)
AttributeError: 'WSGIRequest' object has no attribute 'success'
2021-11-29 20:10:44,641 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:10:46,303 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:10:56,864 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:10:57,806 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:01,887 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:03,045 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:05,932 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:07,155 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:08,831 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:09,706 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:11,470 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:12,664 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:16,825 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:18,181 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:20,168 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:21,213 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:28,409 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:29,350 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:37,669 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:38,681 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:40,512 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:41,456 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:44,448 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:45,356 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:47,118 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:48,176 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:11:50,041 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:11:51,385 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:12:55,476 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:12:56,403 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:12:58,420 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:12:59,562 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:13:15,363 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:13:16,774 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:13:20,421 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:13:21,338 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:13:35,254 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:13:36,131 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:13:52,944 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:13:54,322 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:13:58,097 [ERROR] django.request: Internal Server Error: /faq/eamil
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 108, in email
    return render(request, 'management.html', {'users': user, 'data': user.email})
AttributeError: 'QuerySet' object has no attribute 'email'
2021-11-29 20:16:50,832 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:16:51,961 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:16:56,189 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:16:57,546 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:17:00,609 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:17:01,640 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:17:06,906 [ERROR] django.request: Internal Server Error: /faq/eamil
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 107, in email
    user_email=user.email
AttributeError: 'QuerySet' object has no attribute 'email'
2021-11-29 20:17:41,925 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:17:43,205 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:17:47,472 [ERROR] django.request: Internal Server Error: /faq/eamil
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 107, in email
    user_email=user.email
AttributeError: 'QuerySet' object has no attribute 'email'
2021-11-29 20:18:47,937 [ERROR] django.request: Internal Server Error: /faq/eamil
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 107, in email
    user_email=user.email
AttributeError: 'QuerySet' object has no attribute 'email'
2021-11-29 20:20:20,794 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:20:22,089 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:20:26,905 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:20:28,072 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:20:34,830 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:20:35,638 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:20:42,415 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:20:43,338 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:20:49,148 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:20:50,303 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:20:53,850 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:20:54,937 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:20:57,384 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:20:58,573 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:21:01,109 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:21:02,284 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:21:04,888 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:21:05,770 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:21:23,312 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:21:24,532 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:21:43,294 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:21:44,800 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:21:57,976 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:21:59,039 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:22:19,243 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:22:20,457 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:22:29,949 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:22:32,073 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:22:44,857 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\notice\settings.py changed, reloading.
2021-11-29 20:22:45,873 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:22:47,617 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\notice\settings.py changed, reloading.
2021-11-29 20:22:48,722 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:22:52,786 [INFO] faq.views: user.email = 1234@gmail.com
2021-11-29 20:22:54,121 [INFO] faq.views: user.email = 1234@gmail.com
2021-11-29 20:23:24,661 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:23:26,006 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:23:30,324 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:23:31,515 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:23:33,264 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:23:34,283 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:23:37,157 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:23:38,081 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:23:41,061 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:23:42,423 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:23:44,320 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:23:45,825 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:23:46,344 [INFO] faq.views: users = <QuerySet [<User: 1234>]>
2021-11-29 20:23:46,349 [INFO] faq.views: user.email = 1234@gmail.com
2021-11-29 20:24:39,397 [INFO] accounts.views: username = admin
2021-11-29 20:24:39,584 [INFO] accounts.views: user = admin
2021-11-29 20:24:45,672 [INFO] faq.views: users = <QuerySet [<User: 1234>, <User: 12345>]>
2021-11-29 20:24:45,675 [INFO] faq.views: user.email = 1234@gmail.com
2021-11-29 20:24:45,676 [INFO] faq.views: user.email = 12345@gmail.com
2021-11-29 20:25:16,729 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:25:17,862 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:25:19,951 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:25:21,035 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:25:22,918 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:25:23,859 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:25:29,056 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:25:30,273 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:25:32,036 [INFO] faq.views: user_email = ['1234@gmail.com', '12345@gmail.com']
2021-11-29 20:25:33,331 [INFO] faq.views: user_email = ['1234@gmail.com', '12345@gmail.com']
2021-11-29 20:25:56,380 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:25:57,356 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:25:59,229 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:26:00,172 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:26:04,048 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:26:05,243 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:26:07,784 [INFO] faq.views: user_email = ['1234@gmail.com', '12345@gmail.com']
2021-11-29 20:26:07,785 [ERROR] django.request: Internal Server Error: /faq/eamil
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 111, in email
    logger.info('user.email = {}'.format(users.email))
AttributeError: 'QuerySet' object has no attribute 'email'
2021-11-29 20:26:12,959 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:26:13,846 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:26:15,763 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:26:16,916 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:26:23,020 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:26:24,018 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:26:30,120 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:26:30,979 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:26:37,008 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:26:37,928 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:26:47,123 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:26:48,014 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:27:13,339 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:27:14,732 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:27:17,386 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:27:18,302 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:27:42,965 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:27:43,951 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:27:48,672 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:27:49,664 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:27:57,063 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:27:58,261 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:28:02,031 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:28:03,188 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:28:07,157 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:28:08,020 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:28:18,977 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:28:20,075 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:28:31,611 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:28:32,583 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:28:35,593 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:28:36,554 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:28:41,554 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:28:42,703 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:28:50,046 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:28:51,103 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:28:54,104 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:28:55,074 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:29:00,176 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:29:01,273 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:29:07,317 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:29:08,291 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:29:10,042 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:29:11,186 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:29:13,326 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:29:14,754 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:29:16,602 [INFO] faq.views: user_email = ['1234@gmail.com', '12345@gmail.com']
2021-11-29 20:29:16,602 [INFO] faq.views: user_dept = ['DataScience', 'Computer']
2021-11-29 20:29:16,603 [INFO] faq.views: user_notice = [['ok', 'no', 'no', 'ok'], ['F', 'F', 'T', 'T']]
2021-11-29 20:31:40,582 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:31:41,817 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:31:43,963 [INFO] faq.views: user_email = ['1234@gmail.com', '12345@gmail.com']
2021-11-29 20:31:43,963 [INFO] faq.views: user_dept = ['DataScience', 'Computer']
2021-11-29 20:31:43,963 [INFO] faq.views: user_notice = [['ok', 'no', 'no', 'ok'], ['F', 'F', 'T', 'T']]
2021-11-29 20:31:47,792 [INFO] faq.views: user_email = ['1234@gmail.com', '12345@gmail.com']
2021-11-29 20:31:47,792 [INFO] faq.views: user_dept = ['DataScience', 'Computer']
2021-11-29 20:31:47,792 [INFO] faq.views: user_notice = [['ok', 'no', 'no', 'ok'], ['F', 'F', 'T', 'T']]
2021-11-29 20:31:55,509 [INFO] faq.views: user_email = ['1234@gmail.com', '12345@gmail.com']
2021-11-29 20:31:55,509 [INFO] faq.views: user_dept = ['DataScience', 'Computer']
2021-11-29 20:31:55,509 [INFO] faq.views: user_notice = [['ok', 'no', 'no', 'ok'], ['F', 'F', 'T', 'T']]
2021-11-29 20:31:58,477 [INFO] faq.views: user_email = ['1234@gmail.com', '12345@gmail.com']
2021-11-29 20:31:58,477 [INFO] faq.views: user_dept = ['DataScience', 'Computer']
2021-11-29 20:31:58,477 [INFO] faq.views: user_notice = [['ok', 'no', 'no', 'ok'], ['F', 'F', 'T', 'T']]
2021-11-29 20:32:01,976 [INFO] faq.views: user_email = ['1234@gmail.com', '12345@gmail.com']
2021-11-29 20:32:01,976 [INFO] faq.views: user_dept = ['DataScience', 'Computer']
2021-11-29 20:32:01,976 [INFO] faq.views: user_notice = [['ok', 'no', 'no', 'ok'], ['F', 'F', 'T', 'T']]
2021-11-29 20:33:04,145 [INFO] accounts.views: username = 1234
2021-11-29 20:33:04,327 [INFO] accounts.views: user = 1234
2021-11-29 20:36:38,715 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:36:39,857 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:36:43,833 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:36:44,877 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:36:46,819 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:36:47,762 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:36:49,587 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:36:50,578 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:38:45,758 [INFO] accounts.views: username = 12345
2021-11-29 20:38:45,947 [INFO] accounts.views: user = 12345
2021-11-29 20:43:29,981 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:43:30,905 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:43:32,112 [INFO] faq.views: edit in
2021-11-29 20:43:32,135 [ERROR] django.request: Internal Server Error: /faq/edit
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 27, in edit
    return render(request, 'edit.html')
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit_info' not found. 'edit_info' is not a valid view function or pattern name.
2021-11-29 20:43:42,629 [INFO] faq.views: edit in
2021-11-29 20:43:42,642 [ERROR] django.request: Internal Server Error: /faq/edit
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 27, in edit
    return render(request, 'edit.html')
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit_info' not found. 'edit_info' is not a valid view function or pattern name.
2021-11-29 20:44:07,527 [INFO] faq.views: edit in
2021-11-29 20:45:20,922 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:45:21,981 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:45:33,067 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:45:34,165 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:45:39,860 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:45:41,077 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:45:50,161 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:45:51,105 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:45:55,732 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:45:56,796 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:46:54,367 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:46:55,224 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:46:59,188 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:47:00,082 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:47:48,254 [INFO] faq.views: edit in
2021-11-29 20:50:04,804 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:50:05,726 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:50:22,000 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:50:22,871 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:50:33,987 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:50:35,184 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:50:36,689 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:50:37,565 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:50:39,024 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:50:40,273 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:50:58,809 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:51:00,046 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:51:01,552 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:51:02,671 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:51:05,426 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:51:06,595 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:51:08,608 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:51:09,588 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:53:44,147 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:53:45,464 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:53:54,030 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:53:55,546 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:53:56,983 [WARNING] django.request: Not Found: /faq/edit_info
2021-11-29 20:54:03,229 [INFO] faq.views: edit in
2021-11-29 20:54:03,247 [ERROR] django.request: Internal Server Error: /faq/edit
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 27, in edit
    return render(request, 'edit.html')
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit_link' not found. 'edit_link' is not a valid view function or pattern name.
2021-11-29 20:54:46,180 [INFO] faq.views: edit in
2021-11-29 20:55:42,955 [INFO] faq.views: edit in
2021-11-29 20:56:00,130 [INFO] faq.views: edit in
2021-11-29 20:56:11,568 [INFO] faq.views: edit in
2021-11-29 20:56:58,636 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:57:00,048 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:57:02,994 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:57:03,933 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:57:05,697 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:57:06,564 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:57:21,993 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\urls.py changed, reloading.
2021-11-29 20:57:23,216 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:57:35,597 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:57:36,671 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:57:38,230 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:57:39,109 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:57:49,202 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:57:50,125 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:57:52,029 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:57:53,140 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:58:09,133 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:58:10,113 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:58:15,319 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:58:16,401 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:58:30,038 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:58:31,080 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:58:33,983 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:58:34,830 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:58:38,638 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:58:39,837 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:58:46,991 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:58:47,971 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:58:51,909 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:58:53,005 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:58:54,762 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:58:55,641 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:59:00,161 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:59:01,025 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:59:04,849 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:59:05,648 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:59:11,708 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:59:12,791 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:59:15,666 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:59:16,729 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:59:18,828 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:59:20,316 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:59:27,701 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:59:28,935 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:59:30,833 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:59:32,114 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:59:34,132 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 20:59:36,131 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 20:59:52,558 [ERROR] django.request: Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\accounts\views.py", line 12, in signup
    if request.POST['password1'] == request.POST['password2']:
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password1'
2021-11-29 21:00:40,423 [INFO] faq.views: edit in
2021-11-29 21:00:52,146 [WARNING] django.security.csrf: Forbidden (CSRF token missing or incorrect.): /faq/edit_info
2021-11-29 21:01:34,793 [WARNING] django.security.csrf: Forbidden (CSRF token missing or incorrect.): /faq/edit_info
2021-11-29 21:01:41,401 [INFO] faq.views: edit in
2021-11-29 21:01:53,021 [INFO] faq.views: username=12345
2021-11-29 21:02:14,086 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:02:17,170 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:02:19,025 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:02:19,866 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:02:37,281 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:02:38,508 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:02:39,978 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:02:41,162 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:02:59,925 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:03:01,207 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:03:04,754 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:03:05,771 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:03:13,914 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:03:14,799 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:05:06,549 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:05:07,593 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:05:21,407 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:05:22,464 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:05:48,409 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:05:49,751 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:05:52,720 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:05:53,537 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:06:01,625 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:06:02,740 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:06:07,438 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:06:08,233 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:06:11,755 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:06:12,651 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:06:15,565 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:06:16,540 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:06:19,987 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:06:20,992 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:06:22,843 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:06:23,819 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:06:35,207 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:06:36,557 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:06:40,859 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:06:42,008 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:06:44,783 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:06:45,814 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:07:05,785 [INFO] faq.views: username=12345
2021-11-29 21:07:05,787 [ERROR] django.request: Internal Server Error: /faq/edit_info
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 34, in edit_info
    user.email=request.POST['email']
AttributeError: 'NoneType' object has no attribute 'email'
2021-11-29 21:08:08,864 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:08:10,125 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:08:15,080 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:08:16,370 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:08:18,172 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:08:19,211 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:08:24,265 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:08:25,341 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:08:27,168 [INFO] faq.views: username=12345
2021-11-29 21:08:27,170 [INFO] faq.views: user=None
2021-11-29 21:08:27,177 [ERROR] django.request: Internal Server Error: /faq/edit_info
Traceback (most recent call last):
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\1114n\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py", line 35, in edit_info
    user.email=request.POST['email']
AttributeError: 'NoneType' object has no attribute 'email'
2021-11-29 21:09:01,434 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:09:02,772 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:09:04,743 [INFO] faq.views: username=12345
2021-11-29 21:09:04,748 [INFO] faq.views: user=12345
2021-11-29 21:09:04,749 [INFO] faq.views: email=222@gmail.com
2021-11-29 21:09:20,355 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:09:21,545 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:09:29,855 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:09:30,959 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:09:35,987 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:09:37,015 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:09:38,890 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:09:40,077 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:09:42,630 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:09:43,892 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:09:46,684 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:09:47,734 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:09:50,278 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:09:51,231 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:09:56,328 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:09:57,324 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:10:01,279 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:10:02,481 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:10:08,635 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:10:09,767 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:10:14,765 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:10:15,768 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:10:17,484 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:10:18,517 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:10:40,307 [INFO] faq.views: username=12345
2021-11-29 21:10:40,309 [INFO] faq.views: user=12345
2021-11-29 21:10:42,717 [INFO] faq.views: edit in
2021-11-29 21:11:10,319 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:11:11,496 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:11:13,264 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:11:14,119 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:11:16,972 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:11:18,043 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:11:24,786 [INFO] accounts.views: username = admin
2021-11-29 21:11:24,981 [INFO] accounts.views: user = admin
2021-11-29 21:12:08,253 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:12:09,836 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:12:12,681 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:12:13,498 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:12:19,142 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:12:20,099 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:12:22,015 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:12:23,215 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:12:55,217 [INFO] accounts.views: username = 1234
2021-11-29 21:12:55,424 [INFO] accounts.views: user = 1234
2021-11-29 21:12:59,785 [INFO] faq.views: edit in
2021-11-29 21:13:12,643 [INFO] faq.views: username=1234
2021-11-29 21:13:12,646 [INFO] faq.views: user=1234
2021-11-29 21:13:20,139 [INFO] faq.views: edit in
2021-11-29 21:14:06,919 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:14:07,930 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:14:09,825 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:14:11,129 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:14:20,376 [INFO] faq.views: username=1234
2021-11-29 21:14:20,378 [INFO] faq.views: user=1234
2021-11-29 21:14:28,376 [INFO] faq.views: edit in
2021-11-29 21:14:31,733 [INFO] faq.views: edit in
2021-11-29 21:15:23,094 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:15:24,279 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:15:35,802 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:15:36,930 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:15:42,008 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:15:43,276 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:15:54,038 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:15:55,453 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:15:57,453 [INFO] faq.views: edit in
2021-11-29 21:16:13,165 [INFO] faq.views: username=1234
2021-11-29 21:16:13,171 [INFO] faq.views: user=1234
2021-11-29 21:16:13,191 [INFO] faq.views: edit in
2021-11-29 21:16:26,945 [INFO] accounts.views: username = admin
2021-11-29 21:16:27,141 [INFO] accounts.views: user = admin
2021-11-29 21:16:42,037 [INFO] accounts.views: username = 1234
2021-11-29 21:16:42,237 [INFO] accounts.views: user = 1234
2021-11-29 21:16:45,534 [INFO] faq.views: edit in
2021-11-29 21:17:31,831 [INFO] faq.views: username=1234
2021-11-29 21:17:31,834 [INFO] faq.views: user=1234
2021-11-29 21:17:31,857 [INFO] faq.views: edit in
2021-11-29 21:17:50,497 [INFO] faq.views: username=1234
2021-11-29 21:17:50,499 [INFO] faq.views: user=1234
2021-11-29 21:17:50,518 [INFO] faq.views: edit in
2021-11-29 21:18:10,641 [INFO] accounts.views: username = admin
2021-11-29 21:18:10,850 [INFO] accounts.views: user = admin
2021-11-29 21:18:19,378 [INFO] faq.views: user_email = ['1234@gmail.com', '123@gmail.com']
2021-11-29 21:18:19,379 [INFO] faq.views: user_dept = ['Software', 'Computer']
2021-11-29 21:18:19,379 [INFO] faq.views: user_notice = [['T', 'F', 'T', 'T'], ['T', 'T', 'T', 'T']]
2021-11-29 21:18:35,954 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:18:36,779 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:19:07,065 [INFO] accounts.views: username = 1234
2021-11-29 21:19:07,251 [INFO] accounts.views: user = 1234
2021-11-29 21:20:12,234 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:20:13,334 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:20:34,562 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:20:35,579 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:22:02,508 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\faq\views.py changed, reloading.
2021-11-29 21:22:03,656 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:24:02,395 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\notice\settings.py changed, reloading.
2021-11-29 21:24:03,460 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:24:09,120 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\notice\settings.py changed, reloading.
2021-11-29 21:24:09,935 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2021-11-29 21:24:21,730 [INFO] accounts.views: username = admin
2021-11-29 21:24:21,931 [INFO] accounts.views: user = admin
2021-11-29 21:25:24,555 [INFO] django.utils.autoreload: C:\Users\1114n\Desktop\Smart.Notice.Bot\notice\notice\settings.py changed, reloading.
2021-11-29 21:25:25,525 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
